name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed successfully"
          npm list --depth=0

      - name: Build project
        run: |
          echo "Starting build process..."
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Checking vite config..."
          cat vite.config.ts
          echo "Running build..."
          npm run build || {
            echo "Build failed, trying simple config..."
            npm run build:simple || {
              echo "Simple build also failed, trying direct vite..."
              npx vite build --config vite.config.simple.ts
            }
          }
          echo "Build completed, checking output..."
          ls -la dist/ || echo "dist directory not found"
          
      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "Build failed: index.html not found in dist"
            exit 1
          fi
          echo "Build successful - dist directory contents:"
          find dist -type f | head -10

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "juejijiangh-lemon-live-19"
          entrypoint: "main.ts"
          root: "."
